name: build
run-name: oaf-uptime-wrapper-${{ github.ref_name }}-${{ github.run_number }}

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - 'README.md'
      - .hadolin.yml
      - .pre-commit-config.yaml
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Login to Azure registry
        uses: docker/login-action@v3.0.0
        with:
          registry: oaftech.azurecr.io
          username: ${{ vars.ACR_PULL_USERNAME }}
          password: ${{ secrets.ACR_PULL_PASSWORD }}

      - name: Set image tags
        id: image_tags
        run: |
          REPO=oaftech.azurecr.io/oneacrefund
          IMAGE=uptime-wrapper-api

          VERSION=$(echo ${GITHUB_REF#refs/tags/v} | sed 's/\//-/g')
          TAGS="${REPO}/${IMAGE}:v${VERSION},${REPO}/${IMAGE}:latest"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.2.0
        with:
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: ${{ steps.image_tags.outputs.tags }}
          context: ${{ github.workspace }}

 
